Repository greedy-team/zup-zup-be, pull requests merged in 2025-08, with the labels that each got.

#12 feat: 카테고리 조회 관련 API 구현
  src/main/java/com/greedy/zupzup/alert/KeywordAlert.java
  src/main/java/com/greedy/zupzup/category/application/CategoryService.java
  src/main/java/com/greedy/zupzup/category/application/dto/CategoryDto.java
  src/main/java/com/greedy/zupzup/category/application/dto/FeatureOptionDto.java
  src/main/java/com/greedy/zupzup/category/application/dto/FeatureWithOptionsDto.java
  src/main/java/com/greedy/zupzup/category/domain/Category.java
  src/main/java/com/greedy/zupzup/category/domain/Feature.java
  src/main/java/com/greedy/zupzup/category/domain/FeatureOption.java
  src/main/java/com/greedy/zupzup/category/exception/CategoryException.java
  src/main/java/com/greedy/zupzup/category/presentation/CategoryController.java
  src/main/java/com/greedy/zupzup/category/presentation/dto/CategoriesResponse.java
  src/main/java/com/greedy/zupzup/category/presentation/dto/CategoryFeaturesResponse.java
  src/main/java/com/greedy/zupzup/category/repository/CategoryRepository.java
  src/main/java/com/greedy/zupzup/category/repository/FeatureOptionRepository.java
  src/main/java/com/greedy/zupzup/lostitem/LostItem.java
  src/main/java/com/greedy/zupzup/lostitem/LostItemFeature.java
Labels: ✨ Feature

#17 feat: 분실물 전체 조회 기능 구현
  src/main/java/com/greedy/zupzup/global/exception/GlobalExceptionHandler.java
  src/main/java/com/greedy/zupzup/lostitem/application/LostItemListService.java
  src/main/java/com/greedy/zupzup/lostitem/application/LostItemSummaryService.java
  src/main/java/com/greedy/zupzup/lostitem/application/dto/LostItemListCommand.java
  src/main/java/com/greedy/zupzup/lostitem/application/dto/LostItemSummaryCommand.java
  src/main/java/com/greedy/zupzup/lostitem/presentation/LostItemListController.java
  src/main/java/com/greedy/zupzup/lostitem/presentation/LostItemSummaryController.java
  src/main/java/com/greedy/zupzup/lostitem/presentation/dto/LostItemListQuery.java
  src/main/java/com/greedy/zupzup/lostitem/presentation/dto/LostItemListResponse.java
  src/main/java/com/greedy/zupzup/lostitem/presentation/dto/LostItemResponse.java
  src/main/java/com/greedy/zupzup/lostitem/presentation/dto/LostItemSummaryResponse.java
  src/main/java/com/greedy/zupzup/lostitem/presentation/dto/PageInfoResponse.java
  src/main/java/com/greedy/zupzup/lostitem/repository/LostItemImageRepository.java
  src/main/java/com/greedy/zupzup/lostitem/repository/LostItemListProjection.java
  src/main/java/com/greedy/zupzup/lostitem/repository/LostItemRepository.java
  src/main/java/com/greedy/zupzup/lostitem/repository/LostItemSummaryRepository.java
  src/main/java/com/greedy/zupzup/lostitem/repository/RepresentativeImageProjection.java
Labels: ✨ Feature

#33 test: 분실물 등록 기능 테스트 작성
  src/main/java/com/greedy/zupzup/TestDataLoader.java
  src/main/java/com/greedy/zupzup/category/repository/FeatureRepository.java
  src/main/java/com/greedy/zupzup/global/exception/CommonException.java
  src/main/java/com/greedy/zupzup/global/exception/GlobalExceptionHandler.java
  src/main/resources/application.yml
  src/test/java/com/greedy/zupzup/common/ControllerTest.java
  src/test/java/com/greedy/zupzup/common/fixture/CategoryFixture.java
  src/test/java/com/greedy/zupzup/common/fixture/FeatureFixture.java
  src/test/java/com/greedy/zupzup/common/fixture/FeatureOptionFixture.java
  src/test/java/com/greedy/zupzup/common/fixture/SchoolAreaFixture.java
  src/test/java/com/greedy/zupzup/global/infrastructure/S3ImageFileManagerTest.java
  src/test/java/com/greedy/zupzup/lostitem/application/LostItemRegisterServiceTest.java
  src/test/java/com/greedy/zupzup/lostitem/presentation/LostItemControllerTest.java
  src/test/java/com/greedy/zupzup/schoolarea/presentation/SchoolAreaControllerTest.java
  src/test/resources/truncate.sql
Labels: ✅ Test

#34 test: 분실물 찾기(퀴즈) 기능 테스트 코드 작성
  src/main/java/com/greedy/zupzup/lostitem/application/LostItemDetailViewService.java
  src/main/java/com/greedy/zupzup/lostitem/repository/LostItemFeatureRepository.java
  src/main/java/com/greedy/zupzup/lostitem/repository/LostItemRepository.java
  src/test/java/com/greedy/zupzup/common/ControllerTest.java
  src/test/java/com/greedy/zupzup/common/ServiceUnitTest.java
  src/test/java/com/greedy/zupzup/common/fixture/CategoryFixture.java
  src/test/java/com/greedy/zupzup/common/fixture/LostItemFeatureFixture.java
  src/test/java/com/greedy/zupzup/common/fixture/LostItemFixture.java
  src/test/java/com/greedy/zupzup/common/fixture/LostItemImageFixture.java
  src/test/java/com/greedy/zupzup/common/fixture/MemberFixture.java
  src/test/java/com/greedy/zupzup/common/fixture/QuizAttemptFixture.java
  src/test/java/com/greedy/zupzup/quiz/application/QuizGenerationServiceTest.java
  src/test/java/com/greedy/zupzup/quiz/application/QuizSubmissionServiceTest.java
  src/test/java/com/greedy/zupzup/quiz/presentation/QuizControllerTest.java
Labels: ✅ Test

#35 test: 카테고리 조회 기능 테스트 코드 작성
  src/main/java/com/greedy/zupzup/category/application/CategoryService.java
  src/main/java/com/greedy/zupzup/category/repository/CategoryRepository.java
  src/test/java/com/greedy/zupzup/category/application/CategoryServiceTest.java
  src/test/java/com/greedy/zupzup/category/presentation/CategoryControllerTest.java
  src/test/java/com/greedy/zupzup/common/ServiceUnitTest.java
Labels: ✅ Test

#39 feat: 로그인 기능 개발
  build.gradle
  src/main/java/com/greedy/zupzup/DataLoader.java
  src/main/java/com/greedy/zupzup/auth/application/AuthService.java
  src/main/java/com/greedy/zupzup/auth/application/dto/LoginCommand.java
  src/main/java/com/greedy/zupzup/auth/application/dto/PortalLoginCommand.java
  src/main/java/com/greedy/zupzup/auth/application/dto/SejongAuthInfo.java
  src/main/java/com/greedy/zupzup/auth/application/dto/SignupCommand.java
  src/main/java/com/greedy/zupzup/auth/exception/AuthException.java
  src/main/java/com/greedy/zupzup/auth/infrastructure/BCryptPasswordEncoder.java
  src/main/java/com/greedy/zupzup/auth/infrastructure/PasswordEncoder.java
  src/main/java/com/greedy/zupzup/auth/infrastructure/SejongAuthenticator.java
  src/main/java/com/greedy/zupzup/auth/jwt/JwtTokenProvider.java
  src/main/java/com/greedy/zupzup/auth/presentation/AuthController.java
  src/main/java/com/greedy/zupzup/auth/presentation/AuthControllerDocs.java
  src/main/java/com/greedy/zupzup/auth/presentation/annotation/MemberAuth.java
  src/main/java/com/greedy/zupzup/auth/presentation/argumentresolver/LoginMember.java
  src/main/java/com/greedy/zupzup/auth/presentation/argumentresolver/LoginMemberArgumentResolver.java
  src/main/java/com/greedy/zupzup/auth/presentation/dto/LoginRequest.java
  src/main/java/com/greedy/zupzup/auth/presentation/dto/LoginResponse.java
  src/main/java/com/greedy/zupzup/auth/presentation/dto/PortalLoginRequest.java
  src/main/java/com/greedy/zupzup/auth/presentation/dto/SignupRequest.java
  src/main/java/com/greedy/zupzup/auth/presentation/dto/SignupResponse.java
  src/main/java/com/greedy/zupzup/auth/presentation/dto/VerifiedStudentResponse.java
  src/main/java/com/greedy/zupzup/auth/presentation/interceptor/AuthInterceptor.java
  src/main/java/com/greedy/zupzup/global/config/HttpClientConfig.java
  src/main/java/com/greedy/zupzup/global/config/S3Config.java
  src/main/java/com/greedy/zupzup/global/config/SwaggerConfig.java
  src/main/java/com/greedy/zupzup/global/config/WebConfig.java
  src/main/java/com/greedy/zupzup/global/infrastructure/SwaggerConfig.java
  src/main/java/com/greedy/zupzup/global/util/CookieUtil.java
  src/main/java/com/greedy/zupzup/lostitem/presentation/LostItemController.java
  src/main/java/com/greedy/zupzup/lostitem/presentation/LostItemDetailViewController.java
  src/main/java/com/greedy/zupzup/member/domain/Member.java
  src/main/java/com/greedy/zupzup/member/domain/Provider.java
  src/main/java/com/greedy/zupzup/member/repository/MemberRepository.java
  src/main/resources/application.yml
  src/test/java/com/greedy/zupzup/auth/application/AuthServiceTest.java
  src/test/java/com/greedy/zupzup/auth/presentation/AuthControllerTest.java
  src/test/java/com/greedy/zupzup/common/ControllerTest.java
  src/test/java/com/greedy/zupzup/common/fixture/MemberFixture.java
Labels: ✨ Feature

#43 feat: Logback과 AOP를 활용한 로깅 전략 수립
  .gitignore
  build.gradle
  src/main/java/com/greedy/zupzup/global/config/WebConfig.java
  src/main/java/com/greedy/zupzup/global/presentation/LogFilter.java
  src/main/java/com/greedy/zupzup/global/presentation/interceptor/LogInterceptor.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/main/resources/logback/console/error-console.xml
  src/main/resources/logback/console/info-console.xml
  src/main/resources/logback/console/warn-console.xml
  src/main/resources/logback/file/error-appender.xml
  src/main/resources/logback/file/info-appender.xml
  src/main/resources/logback/file/warn-appender.xml
Labels: ✨ Feature

#53 fix: 배포 스크립트 파일 로그경로 수정
  script/deploy.sh
Labels: 🐞 BugFix

#56 fix: 배포 스크립트 로그 오류 수정
  script/deploy.sh
Labels: 🐞 BugFix

#64 fix: 쿠키 설정 수정
  src/main/java/com/greedy/zupzup/global/config/WebConfig.java
  src/main/java/com/greedy/zupzup/global/util/CookieUtil.java
Labels: 🐞 BugFix
